version: "3.6"
services:
  django:
    image: simplest-docker-example
    environment:
     - MAGIC_MESSAGE=Docker Compose
     - SECRET_KEY=23408728djlkjd37nmckdllsorhh377889s900&&^623
    ports:
      - "8000:8000"